
import "./prueba.css";
import Link from 'next/link'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <nav>
          <Link href="/">Home</Link>
          <Link href="/dashboards">Dashboards</Link>
          <Link href="/databases">Databases</Link>
          <Link href="/settings">Settings</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
